services:

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass password

  zibbit_web:
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.local
    depends_on:
      - redis
    volumes:
      - ./app:/app