version: '3.8'

services:

  client1:
    build: 
      context: ./client
    depends_on:
      - web
    environment:
      - NAME=client1
      - TARGET=http://web:5000

  client2:
    build: 
      context: ./client
    depends_on:
      - web
    environment:
    - NAME=client2
    - TARGET=http://web:5000

  client3:
    build: 
      context: ./client
    depends_on:
      - web
    environment:
    - NAME=client3
    - TARGET=http://web:5000


  web:
    build: .
    ports:
      - "8080:5000"
    depends_on:
      - redis
    environment:
      - FLASK_APP=main.py
      - FLASK_RUN_HOST=0.0.0.0

  redis:
    image: redis:7-alpine
