services:

  redis:
    image: redis:7-alpine

  zibbit_web:
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    volumes:
      - ./app:/app
      - ./.env:/.env